# The bot population. ~200 bots generated by {Bots::Roster} — a population pyramid
# of kung-fu-movie names across belts 0..17, each with a belt-scaled brain and a
# persona (activity window, aggression, temperament) that the per-minute
# Bots::TickJob drives. Idempotent: re-running only fills in missing bots and never
# disturbs an existing bot's accumulated XP, record, or belt.
#
# Deterministic given the roster seed, so the generated names are stable across
# re-seeds and the fill-in stays a true no-op once the roster exists.

specs = Bots::Roster.generate

created = 0
specs.each do |spec|
  fighter = Fighter.find_or_initialize_by(name: spec[:name])
  next if fighter.persisted?

  fighter.assign_attributes(
    bot: true,
    belt: spec[:belt],
    xp: Bots::Roster.seed_xp(spec[:belt], Random.new(spec[:name].hash)),
    strategy: spec[:strategy].deep_stringify_keys,
    last_seen_at: nil
  )
  fighter.save!
  created += 1
end

by_belt = Fighter.bots.group(:belt).count.sort.to_h
puts "Seeded bots: #{Fighter.bots.count} total (#{created} new this run)."
puts "Belt spread: #{by_belt.map { |belt, n| "#{Belt.name_for(belt)}=#{n}" }.join('  ')}"
